layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: ash-ma1989
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://ashma.info
  # youtube: your_username

topics:
  - name: PPIO
    web_url: https://pp.io/?from=ash
    image_url: https://media.licdn.com/dms/image/C510BAQGJ0BNE7Zoa4g/company-logo_100_100/0?e=1562803200&v=beta&t=C9_auklRbeDzA9Wj_QJmbEw_1mAkXT5smYXjY23qkYk

  - name: We are hiring
    web_url: https://www.zhipin.com/gongsir/5ba2ae5248837b0d1n192Nq0FQ~~.html?ka=company-jobs/?ash
    image_url: https://d3nbup7htlluyi.cloudfront.net/5c00b8ef5da4962f66df2d92/logo/89a32ce3bd106b7261b2098d095e25ed67ocqvqq.png

  - name: About Me
    web_url: https://www.linkedin.com/in/ash-ma1989/?ash
    image_url: https://ss0.bdstatic.com/-0U0bnSm1A5BphGlnYG/tam-ogel/ae60db54936bb024336e75c7c90a8578_121_121.jpg

theme: jekyll-theme-cayman
